language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  - UPGRADE=none
  - UPGRADE=7.x-3.9
  - UPGRADE=7.x-3.8
  - UPGRADE=7.x-3.7
  - UPGRADE=7.x-3.6
  - UPGRADE=7.x-3.5

matrix:
  allow_failures:
    - env: UPGRADE=7.x-3.9
    - env: UPGRADE=7.x-3.8
    - env: UPGRADE=7.x-3.7
    - env: UPGRADE=7.x-3.6
    - env: UPGRADE=7.x-3.5

install:
  # Add the Google Chrome packages.
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update > /dev/null

  # Create a database for our Drupal site.
  - "mysql -e 'create database drupal;'"

  # Install the latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --prefer-source --no-interaction drush/drush:6.*@dev

  # Build Behat dependencies
  - cd ./tests/behat
  - composer install --prefer-source --no-interaction
  - cd ../../../

  # Rename the repository folder to 'commons' (to accommodate different repository names).
  - REPO_NAME=`basename $TRAVIS_REPO_SLUG`
  - mv $REPO_NAME commons

  # Build Codebase
  - mkdir profiles
  - mv commons profiles/
  - mkdir drupal
  - mv profiles drupal/

  # Test the current branch
  - cd drupal
  - drush make --yes profiles/commons/drupal-org-core.make --prepare-install
  - drush make --yes profiles/commons/drupal-org.make --no-core --contrib-destination=profiles/commons
  - mkdir sites/default/private
  - mkdir sites/default/private/files
  - mkdir sites/default/private/temp
  - cd ../

  # Download an old version to test upgrading from.
  - if [[ "$UPGRADE" != none ]]; then drush dl commons-$UPGRADE; fi

  # Setup files
  - sudo chmod -R 777 drupal/sites/all

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Chrome and ChromeDriver
  - sudo apt-get install google-chrome-stable
  - wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
  - unzip -a chromedriver_linux64.zip

  # Insane hack from jsdevel:
  #   https://github.com/jsdevel/travis-debugging/blob/master/shim.bash
  # This allows chrome-sandbox to work in side of OpenVZ, because I can't
  # figure out how to start chrome with --no-sandbox.
  - export CHROME_SANDBOX=/opt/google/chrome/chrome-sandbox
  - sudo rm -f $CHROME_SANDBOX
  - sudo wget https://googledrive.com/host/0B5VlNZ_Rvdw6NTJoZDBSVy1ZdkE -O $CHROME_SANDBOX
  - sudo chown root:root $CHROME_SANDBOX; sudo chmod 4755 $CHROME_SANDBOX
  - sudo md5sum $CHROME_SANDBOX

  # Get Selenium
  - wget http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar
  - java -jar selenium-server-standalone-2.41.0.jar -Dwebdriver.chrome.driver=`pwd`/chromedriver > /dev/null 2>&1 &
  - sleep 5
 
  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:

  # Do the site install (either the current revision or old for the upgrade).
  - if [[ "$UPGRADE" == none ]]; then cd drupal; else cd commons-$UPGRADE; fi
  - drush si commons --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --account-mail=admin@test.com --site-mail=noreply@test.com --site-name="Commons" --yes
  - drush vset -y file_private_path "sites/default/private/files"
  - drush vset -y file_temporary_path "sites/default/private/temp"
  - cd ../drupal

  # If we're an upgrade test, run the upgrade process.
  - if [[ "$UPGRADE" != none ]]; then cp -a ../commons-$UPGRADE/sites/default/* sites/default/ && drush updb --yes; fi

  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - SERVER_PID=$!
  - sleep 3
  - cd profiles/commons/tests/behat

  # Make the Travis tests repos agnostic by injecting drupal_root with BEHAT_PARAMS
  - BUILD_OWNER=`dirname $TRAVIS_BUILD_DIR`
  - export BEHAT_PARAMS="extensions[Drupal\\DrupalExtension\\Extension][drupal][drupal_root]=$BUILD_OWNER/drupal"

script:

  # First, run all the tests in Firefox.
  - ./bin/behat --config behat.travis.yml
 
  # Then run some Chrome-only tests.
  - ./bin/behat --config behat.travis.yml -p chrome

after_script:

  # Stop the webserver so that it's not still running when MySQL is stopped.
  - kill $SERVER_PID

notifications:
  email:
    recipients:
      - commons-bulk@acquia.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#drupal-commons"
    on_success: change
    on_failure: always
